pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                stash includes: '/var/jenkins_home/workspace/notsodummy/target/my-app-1.0-SNAPSHOT.jar', name: 'mynotsodummy'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('DockerBuild'){
            agent any             
            
            steps{
                unstash 'mynotsodummy'
                docker version
            }
            
        }
    }
}
